<?php
/** @var \Magento\Framework\View\Element\Template $block */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

/** @var \Magento\Framework\Escaper $escaper */
?>
<form class="form-address-edit"
      action="<?= $escaper->escapeUrl($block->getUrl('car/edit/editPost')) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Car Profile')) ?></span></legend><br>
        <?= $block->getBlockHtml('formkey') ?>
        <div class="field car required">
            <label class="label" for="car"><span><?= $block->escapeHtml(__('Select Make')) ?></span></label>
            <div class="control">
                <select id="makes">
                    <option value=""><?= __('Select Make...') ?></option>
                </select>
            </div>
        </div>
        <div class="field car-field required" style="display: none;">
            <label class="label" for="car"><span><?= $block->escapeHtml(__('Select Car')) ?></span></label>
            <div class="control">
                <div data-bind="scope: 'carprofile'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset">
        <div data-bind="scope: 'preview'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $escaper->escapeHtmlAttr(__('Save')) ?>"
                disabled="disabled">
                <span><?= $block->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
<?php
$scriptString = <<<script
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');


    });
script;
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "carprofile": {
                        "component": "Razoyo_CarProfile/js/form/element/car-profile-select",
                        "template" : "Razoyo_CarProfile/ui/form/element/car-select"
                    },
                    "preview": {
                        "component": "Razoyo_CarProfile/js/view/preview-car",
                        "template" : "Razoyo_CarProfile/preview"
                    }
                }
            }
        }
    }
</script>
<script>
    requirejs(
        [
            'Razoyo_CarProfile/js/action/get-car-list',
            'Razoyo_CarProfile/js/model/makes',
            'Razoyo_CarProfile/js/model/make-selected-value',
            'underscore',
            'jquery',
            'domReady!'
        ], function (GetCarListAction, makes, makeSelectedValue, _, $) {

            $(document).ready(function () {
                GetCarListAction('').then(function (response, textStatus, xhr) {
                    if (response.makes !== undefined && response.makes.length) {
                        _.each(response.makes, function (make) {
                            $('#makes').append('<option value="' + make + '">' + make + '</option>');
                        });
                        let yourToken = xhr.getResponseHeader('your-token');
                        console.log('response header:', yourToken);
                    }
                });

                $("#makes").on("change", function (e) {
                    e.preventDefault();

                    if (this.value.trim() !== '') {
                        makeSelectedValue(this.value);
                        $('.car-field').show();
                    } else {
                        $('.car-field').hide();
                        makeSelectedValue('');
                        $('[type="submit"]').attr('disabled', 'disabled');
                    }
                });
            });
        });
</script>
